### ISSUE TITLE
Add content for demonstration purposes

### ISSUE THREAD

**Issue by vkechagias** [morethanthemes/magazine-lite#1]
- [x] Προσθήκη 4 articles με περιεχόμενο όμοιο με το magazineplus.
  Σε κάθε ένα απο τα παραπάνω articles να ορίσουμε taxonomy term κάποια απο τα παρακάτω ώστε κάθε term να έχει τουλάχιστον 2 articles:
    - Health
    - Lifestyle
    - Sports

- [x] Προσθήκη των παρακάτω basic pages όπως είναι στο magazineplus
  - Style Guide
  - Shortcodes
  - About (χωρίς το view)

- [x] Προσθήκη basic pages για responsive grid όμοια με http://demo.drupalizing.com/showcase-lite/site/node/3 και http://demo.drupalizing.com/showcase-lite/site/node/4

- [x] Προσθήκη menu items στο main menu που θα στέλνουν στα taxonomy term pages των article terms
- [x] Προσθήκη menu items στο main menu που θα στέλνουν στα παραπάνω basic pages
- [x] Ενεργοποίηση contact form και προσθήκη σχετικού menu item στο main menu

**Comment by abatsakidis** [comment]
@vkechagias σχετικά με τα articles. Έχω κάνει το taxonomy με τις 3 λέξεις που αναφέρεις. Τα άρθρα πώς θα τα κατηγοροποιήσω? δεν υπάρχει πεδίο post category στο article. Θα αναφέρω τις κατηγορίες στο πεδίο tags απλά?

**Comment by vkechagias** [comment]
@abatsakidis Στο field που ήδη υπάρχει πρεπει να τα ορίσεις. Νομίζω ειναι το tags. Δεν χρειάζεται να τα προσθέσεις απο πριν στο vocabulary. 

Αν τα προσθέσεις στο field θα αποθηκευτούν κανονικά. 

Ας το δούμε και μαζι αύριο στο γραφείο.
