### ISSUE TITLE
Upgrade Magazineplus-lite to Drupal 10

### ISSUE THREAD

**Issue by GeorgeKonispoliatis** [morethanthemes/magazine-lite#13]

**Comment by BSimon47** [comment]
George,

 

I can see that you are working on Drupal 10 compliance with the Magazine Lite theme.

I can tell you that I am running Magazine+ 5.11.0 and my theme is already compliant with Drupal 10.3.5.

I had recently asked about Drupal 11 compliance as I am close to moving my Magazine plus themed websites into Drupal 11 has now been released although I am still waiting for some modules to come into compliance.

 

Please advise on the status of Magazine Plus! 

 

Thanks,

 

Bruce A. Simon

Email:  ***@***.***> ***@***.***
